/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CategoryPill: typeof import('./components/CategoryPill.vue')['default']
    DateStrip: typeof import('./components/DateStrip.vue')['default']
    DayCarousel: typeof import('./components/DayCarousel.vue')['default']
    DayEmpty: typeof import('./components/DayEmpty.vue')['default']
    HighlightText: typeof import('./components/HighlightText.vue')['default']
    IssueList: typeof import('./components/IssueList.vue')['default']
    LessonReview: typeof import('./components/LessonReview.vue')['default']
    PracticeMode: typeof import('./components/PracticeMode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentenceCard: typeof import('./components/SentenceCard.vue')['default']
  }
}
