/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CategoryPill: typeof import('./components/CategoryPill.vue')['default']
    CourseProgress: typeof import('./components/CourseProgress.vue')['default']
    DateStrip: typeof import('./components/DateStrip.vue')['default']
    DayCarousel: typeof import('./components/DayCarousel.vue')['default']
    DayEmpty: typeof import('./components/DayEmpty.vue')['default']
    FillBlanks: typeof import('./components/practice/FillBlanks.vue')['default']
    FlashcardDeck: typeof import('./components/practice/FlashcardDeck.vue')['default']
    HighlightText: typeof import('./components/HighlightText.vue')['default']
    IssueList: typeof import('./components/IssueList.vue')['default']
    KnowledgeSummary: typeof import('./components/KnowledgeSummary.vue')['default']
    LessonReview: typeof import('./components/LessonReview.vue')['default']
    PlanGrid: typeof import('./components/PlanGrid.vue')['default']
    PracticeDrawer: typeof import('./components/practice/PracticeDrawer.vue')['default']
    PracticeHub: typeof import('./components/practice/PracticeHub.vue')['default']
    PracticeResult: typeof import('./components/practice/PracticeResult.vue')['default']
    ProgressHeader: typeof import('./components/practice/ProgressHeader.vue')['default']
    QuizExercise: typeof import('./components/practice/QuizExercise.vue')['default']
    RewriteExercise: typeof import('./components/practice/RewriteExercise.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentenceCard: typeof import('./components/SentenceCard.vue')['default']
  }
}
